version: '3.8'
services:
  db:
    image: mysql:8
    container_name: clinic-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clinicdb
      MYSQL_USER: clinicuser
      MYSQL_PASSWORD: clinicpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: smart-clinic-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/clinicdb
      SPRING_DATASOURCE_USERNAME: clinicuser
      SPRING_DATASOURCE_PASSWORD: clinicpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  db_data:
